### ISSUE TITLE
Information on power law samping

### ISSUE THREAD

**Issue by gioiera** [schuhmaj/nasa-breakup-model-cpp#45]
HI! 

Where the equation for transform from uniform to powerlaw (equation (4.1) of your thesis) comes from? 
It doesn't have any normalization factor, you just need to set the rigth exponent for explosion and collision?

The equations (2.6) and (2.7) are used only to set the total amount of debris?

Thank you!

**Comment by schuhmaj** [comment]
Hi,

you can find my answers below:

> Where the equation for transform from uniform to powerlaw (equation (4.1) of your thesis) comes from?

The equation (4.1) originates from StackOverflow [1], which in turn references Wolfram [2].

> It doesn't have any normalization factor, you just need to set the rigth exponent for explosion and collision?

Yes.
Given that the input variable $y \in [0;1]$ is a normally distributed variable, the implemented transformation yields $x \in [x_0, x_1]$ where x is distributed according to a power-law distribution with $n$ as the exponent of the probability density function $f(x)$.
Equations (2.6) and (2.7) are the cumulative distribution functions $F(x)$.
Thus, in order to determine $n$, we need to take the exponent $n$ of the derivative $\frac{d}{dx} F(x) = f(x)$

> The equations (2.6) and (2.7) are used only to set the total amount of debris?

Not only.
Equations (2.6) and (2.7) are the cumulative distribution functions $F(x)$. These $F(x)$ functions, in the thesis denoted with $N(L_c)$ calculate the number of fragments given a minimal characteristic Length $L_c$, as you mentioned.
However, there is also an underlying "message" in the derivative given by their probability density functions $f(x)$.
These are utilized to assign each fragment (whose number was determined earlier by $F(x)$ ) a characteristic Length $L_c$.

[1] https://stackoverflow.com/questions/918736/random-number-generator-that-produces-a-power-law-distribution
[2] https://mathworld.wolfram.com/RandomNumber.html
[3] https://en.wikipedia.org/wiki/Probability_density_function#Further_details

--------

I hope this helps 🙂 Don't hesitate to ask further questions if anything is unclear/ point out errors.

**Comment by gioiera** [comment]
Hi, thank you very much for the answer!

Since I have to implement the SBM for a project, would be available for a brief meeting? I would like to ask you some questions regarding your implementation. 

Just let me know if you are available, otherwise I can write them here without any problem!

**Comment by schuhmaj** [comment]
Sure, a meeting, why not.
What about Tuesday (23.01), Thursday (25.01), or Friday (26.01)? I prefer the afternoon, but I am available the whole day.
(My email for a calendar invite, as stated in GitHub and LinkedIn, is [jonas.schuhmacher@tum.de](mailto:jonas.schuhmacher@tum.de))

**Comment by gioiera** [comment]
Thank you!
I am available on Tuesday afternoon, at which hour? I am totally flexible.

**Comment by schuhmaj** [comment]
Tuesday, 23.01, at 15:00?

**Comment by gioiera** [comment]
Yes perfect, now I send you the invitation to the email, thank you!

**Comment by gioiera** [comment]
Good morning, I have sent you the invitation, see you tomorrow!

**Comment by schuhmaj** [comment]
I got the invite. Thank you 👍However, it is assigned to today.
I’m also okay with today, but to clarify: today or tomorrow?

**Comment by schuhmaj** [comment]
Alright, that was a very fast reaction 🙂
